


CREATE VIEW patient_MH_History
AS SELECT PATIENT.patientID,PATIENT.patientName,BILL.invoiceID,MH_PRESCRIPTION.prescriptionID,
MH_CONSULTATION.consultationID,MH_ADMISSION.admissionID,MH_TEST.testID,MH_SCAN.scanID,MH_SURGERY.surgeryID,DRUGS.drugID

 FROM PATIENT
 INNER JOIN BILL
 ON PATIENT.patientID=BILL.patientID

 INNER JOIN MH_CONSULTATION
 ON BILL.invoiceID=MH_CONSULTATION.invoiceID
 
 INNER JOIN MH_PRESCRIPTION
 ON BILL.invoiceID=MH_PRESCRIPTION.invoiceID
 
 INNER JOIN DRUGS
 ON MH_PRESCRIPTION.drugID=DRUGS.drugID

 ON MH_PRECRIPTION
 INNER JOIN MH_ADMISSION.admissionID=DRUGS.drugID
 
 ON BILL.invoiceID=MH_ADMISSION.invoiceID
 INNER JOIN MH_TEST
 
 ON BILL.invoiceID=MH_TEST.invoiceID
 INNER JOIN MH_SCAN
 
 ON BILL.invoiceID=MH_SCAN.invoiceID
 
 INNER JOIN MH_SURGERY
 ON BILL.invoiceID=MH_SURGERY.invoiceID

